// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: products/understanding/ast/ast_service.proto

package ast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ASTService_Translate_FullMethodName = "/data.speech.ast.ASTService/Translate"
)

// ASTServiceClient is the client API for ASTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ASTServiceClient interface {
	Translate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranslateRequest, TranslateResponse], error)
}

type aSTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewASTServiceClient(cc grpc.ClientConnInterface) ASTServiceClient {
	return &aSTServiceClient{cc}
}

func (c *aSTServiceClient) Translate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranslateRequest, TranslateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ASTService_ServiceDesc.Streams[0], ASTService_Translate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranslateRequest, TranslateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTService_TranslateClient = grpc.BidiStreamingClient[TranslateRequest, TranslateResponse]

// ASTServiceServer is the server API for ASTService service.
// All implementations must embed UnimplementedASTServiceServer
// for forward compatibility.
type ASTServiceServer interface {
	Translate(grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]) error
	mustEmbedUnimplementedASTServiceServer()
}

// UnimplementedASTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedASTServiceServer struct{}

func (UnimplementedASTServiceServer) Translate(grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]) error {
	return status.Error(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedASTServiceServer) mustEmbedUnimplementedASTServiceServer() {}
func (UnimplementedASTServiceServer) testEmbeddedByValue()                    {}

// UnsafeASTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASTServiceServer will
// result in compilation errors.
type UnsafeASTServiceServer interface {
	mustEmbedUnimplementedASTServiceServer()
}

func RegisterASTServiceServer(s grpc.ServiceRegistrar, srv ASTServiceServer) {
	// If the following call panics, it indicates UnimplementedASTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ASTService_ServiceDesc, srv)
}

func _ASTService_Translate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ASTServiceServer).Translate(&grpc.GenericServerStream[TranslateRequest, TranslateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTService_TranslateServer = grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]

// ASTService_ServiceDesc is the grpc.ServiceDesc for ASTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.speech.ast.ASTService",
	HandlerType: (*ASTServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Translate",
			Handler:       _ASTService_Translate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "products/understanding/ast/ast_service.proto",
}
